### ISSUE TITLE
Have to reconnect external storage drawer sd drawer controller every time world loads

### ISSUE THREAD

**Issue by freopt** [refinedmods/refinedstorage#2120]
#### Issue description:
Have to reconnect external storage drawer sd drawer controller every time world loads
#### What happens:
Basically the same thing as #170
#### What you expected to happen:
For that not to happen
#### Steps to reproduce:
1. Make a drawer controller then add external storage
2. Put stuff in drawers
3. Reload world
...

#### Version (make sure you are on the latest version before reporting): 

- Minecraft: 1.12.2
- Forge: 14.23.5.2768
- Refined Storage: 1.6.12

Does this issue occur on a server? [yes/no]
i am in singleplayer
#### If a (crash)log is relevant for this issue, link it here:

[pastebin/gist/etc link here]

**Comment by dclay1983** [comment]
I am having the same issue. I was using EnderIO RS conduit, and swapped it for RS cable to verify and it was still the same. I have to break a cable every time I reload the world.

**Comment by SReject** [comment]
### What Happens
The External Storage cable no longer reads the inventory of Storage Drawers' Drawer Controller after reloading the world.

### What is Expected:
After reloading the world, the External Storage cable continues to read the Storage Drawers' Drawer Controller.

### Steps to reproduce
1. Setup creative Refined Storage('RS') Controller with attached Grid
2. A few blocks away setup a Storage Drawer('SD') Basic Storage Drawer and add cobble to it
3. Place a SD Drawer Controller next to the Basic Storage Drawer
4. Place an RS External Storage cable into the SD controller
5. Run Cable from RS controller to RS External Storage cable
6. Check grid, notice cobble **IS** displayed
7. Save and Quit world then exit minecraft
8. Restart minecraft and reload world
9. Check grid and notice the cobble is **NOT** displayed
10. Break RS External Storage cable and replace
11. Check grid again and notice cobble **IS** displayed

### Version:
Minecraft: 1.12.2
Forge: 14.23.5.2775
Refined Storage: 1.6.12
Storage Drawers: 1.12.2-5.3.8

**Comment by andr9528** [comment]
You don't actually need to break the cable, at least i didn't have to, you just have to make a block update beside it, i.e break or place a block beside it.

**Comment by raoulvdberge** [comment]
I can't reproduce this. When did this problem start? In which version, can you guys pinpoint this for me?

**Comment by freopt** [comment]
Either between 1.6.9 and 1.6.10 or 1.6.10 and 1.6.11. I was playing stoneblock and then the pack updated rs from 1.6.9 to 1.6.11 and then the problem started happening. I force updated rs to 1.6.12 and the problem was still there.

**Comment by raoulvdberge** [comment]
Can you pinpoint an exact version for me?

Is the bug 100% of the time reproduceable?

**Comment by Tahakk** [comment]
I was trying to find out what is this about as it is happening on my server too.
I tried RS only pack and wasn't able to reproduce it.

As for StoneBlock I was able to reproduce it on existing world that I have, but unable to reproduce it on the new world created at 1.0.26/1.0.28/1.0.31 while switching between versions randomly multiple times.

One more observation is that it is just not showing old items that already existed, but only those that are inserted after start. Breaking Drawer Controller is not helping, only re-applying External storage.

**Comment by freopt** [comment]
For me every so often the when I open up the wireless crafting grid it only shows items that were put in after I opened it but simply closing and reopening the grid solves the problem. As far as I can tell this is random though.

**Comment by KevinVM1996** [comment]
I also have drawers not showing up upon entering the world. I am using multiple drawers and the weird thing is only one doesnt load. All the others are fine. i usually break the refined storage controller upon entering the world. and that also resets it.  funny enough i also play on stoneblock with refined storage version: 1.6.11 and storage drawers version: 1.12.2-5.3.7
ill try updating both mods and ill report back soon

**Comment by KevinVM1996** [comment]
After updating i still have the problem this time it seems i am missing more drawer controllers. maybe i wa just lucky before didnt check everytime in the past. its definitly not a problem with distance.
current versions:
refined storage: 1.6.12
storage drawers : 1.12.2-5.3.8

ill keep testing.

**Comment by KevinVM1996** [comment]
After furter testing i found some weird things. when i put 1 item in one of the drawers that dont show up. for example diamond chests then the rf system wil show 1 chest but the drawer contains 2.1k chests if i perform a block update on any of the storage busses or i replace the controller then all drawers show up again. second weird thing is if i log in and i see for example 0 diamond chests and i wait untill one gets autocrafted (so the rf system says there is one chest)  if i try to take the 1 chest from the system then it will pull out a full stack from the drawer. after that stack i cant take any more out.

this might be confusing if u want to i couls record it and send it or talk via discord.

**Comment by KevinVM1996** [comment]
**problem found** i had my base chunkloaded with ftb utilities. after turning of chunkloading in the room where the controller is. everything works now when i log in and i have no more problems i hope this helps you all.

**Comment by raoulvdberge** [comment]
I had the same issue with gold in a compacting drawer. RS would show ingots and nuggets with reversed quantities.

**Comment by oliverrook** [comment]
I would like to say I've had this issue as well several times. I think it must relate to the storage drawers not reporting items stacks correctly, as some of the items still seem to be available on occasion, despite the rest not being so.

**Comment by KevinVM1996** [comment]
Yea i just had the isue again i thought i fixed it. it didnt happen for a long time tho.
yhe only difference is that i updated reborn storage. hmmm

**Comment by KevinVM1996** [comment]
I downgraded back to the previous reborn storage version i was using and everything loads perfect again.
the reason why i updated reborn storage is because yesterday when i updated refined storage i noticed that the big crafting multiblock slowed down very significantly this was solved by updating reborn storage but then the drawers dont load tssss.

**Comment by hcrps** [comment]
> **problem found** i had my base chunkloaded with ftb utilities. after turning of chunkloading in the room where the controller is. everything works when i log in and i have no more problems i hope this helps you all.

I can confirm that I was also experiencing this issue on Stoneblock (With Refined Storage updated to 1.6.12) with my system kept in chunks loaded via FTBUtils. The system didn't cross any boundaries of loaded/unloaded chunks, but did span across several loaded chunks. External storages in both the same chunk as the controller and different chunks were not loaded on relog and I had to break a cable and replace it for the system to recognize them. 

After unloading the chunks via FTBUtils and relogging into the game, I am no longer experiencing the issue.

**Comment by ProxyPlayerHD** [comment]
exact same issue with exact same setup. but why is FTB Util. causing this?

**Comment by SReject** [comment]
> why is FTB Util. causing this?

FTB Util is not the source of this. I do not have FTBU installed(Or any chunk loader for that matter) and still experience the issue. If anything its an aggravateor to the underlying issue.

**Comment by gordoodle** [comment]
Further information. It looks like if you are missing items you can just break/update one external storage and items attached to other external storages show up again.

caveat: My external storages are all showing way over capacity, but I don't know how that impacts anything.

In this case, I'm working with external storages attaches to drawer controllers and autosieves - one for cobble, one for dirt, one for sand, etc. I was missing both cactus seeds and gold ore, which go into different drawer sets and are controlled by different drawer controllers I broke and replaced the external storage that connected to the gold ore controller, and the cactus seeds showed back up as well. Is this some sort of caching problem maybe?

**Comment by DracoClaw** [comment]
so if all it needs is an update to the external storage, an online detector from random things plus maybe a piston, would that be enough?

**Comment by kamaln7** [comment]
It seems like the issue only occurs when FTBUtilities' chunk loader is used on the chunk that contains the drawer controller. I'm using ChickenChunks' Chunk Loader block now and everything works fine.

**Comment by Miner94** [comment]
i found an easy fix just control the system with a lever and turn it off and back on not a permanent fix but it works

**Comment by raoulvdberge** [comment]
Closing this as it's not actionable and there are no clear reproduction steps.

**Comment by servireettueri** [comment]
I'm still having this issue. I'm using the most recent version too.

**Comment by Carlosjrlu** [comment]
Same for me lastest version available for ATM6

**Comment by Goldy93** [comment]
Same issue in 1.16.4, forge ver. 35.1.37, single player mode.  When relogging, items in storage drawers do not appear in refined storage.  If I go into the disk drive and just switch to redstone only mode and then back again, the items in the storage drawers show up and stay that way.  It only happens when entering the world.

**Comment by KDawg1979** [comment]
I am having same issue using most current version of revelation pack

**Comment by ErisNoRNG** [comment]
Also having the same issue in Enigmatica 6 v0.5.20, 1.16.5

**Comment by ViperFour** [comment]
To automate the breaking and placing of the drawer controller to update the external storage I used a detector detecting when my cobblestone (stored in drawers) in my rf system is 0,  then it will activate a destructor breaking the drawer controller and have a constructor place the controller again so you automate the breaking placing thing that I have been doing whenever loading my world.
