### ISSUE TITLE
Refined Storage Version 1.8.4 Exporter/Storage Bus Bug

### ISSUE THREAD

**Issue by Saenaria** [refinedmods/refinedstorage#2593]
Issue description: 
The exporter will only export one item to the drawer then stop and will not craft on export to storage drawers with an external storage bus. 

What happens: 
When an external storage bus, even if the external storage priority is set higher than the drives, is present the exporter does not function properly.

What you expected to happen: 
Expected the exporter to see the drawer it's attached to regardless of if there is an external storage bus present.

Steps to reproduce:
1. Attach exporter and an external storage bus to a storage drawer
2. Attempt to export off the system.
3. Add crafting card and attempt to export an item that needs crafted.
4. Remove the storage bus and watch it work.

This the latest version of the FTB Omnia Pack but not the latest version of Refined Storage.

- Minecraft: 1.15.2
- Forge: 31.2.9
- Refined Storage: 1.8.4
- FTB Omnia Pack 1.5.0

**Comment by Darkere** [comment]
If you connect both an export and an external storage the exporter will continuously extract the item from the external storage and then insert them back in. 

#2591 will add an option to always craft.

**Comment by Saenaria** [comment]
I tried putting a drawer controller between the drawers and the storage bus same result, but one thing I did notice is that the storage bus sees the drawers as being more than full, maybe this contributes to why it stops pulling/crafting from the lower priority drives?
![2020-06-28_18 22 01](https://user-images.githubusercontent.com/36122990/85959789-6fb59880-b96c-11ea-8784-816c50d4a307.png)

**Comment by Darkere** [comment]
You do not understand the issue. It is working just fine as it is intended. 

The exporter will always try to extract the item from the system before trying to craft a new one.  If you connect an external storage to the inventory you are trying to insert items into it will extract items from that inventory too. 
You end up with a loop where the items get extracted and then immediately reinserted. 


The issue with the numbers is (somewhat) fixed in 1.8.5. And has always only been a visual indicator. The functionality ignores it.

**Comment by Saenaria** [comment]
I see, I did misunderstand what you were saying, my apologies. Adding an always craft option will be nice thank you. However the loop will still exist if I, for example, add a new storage drawer to a bank of storage drawers and want to pull an item off of my drives to that storage drawer, correct?

**Comment by Darkere** [comment]
Correct. The current implementation inserts into the highest priority storage and also extracts from the highest priority storage first. 

Use a disk manipulator with a filter to get the items from your drives into the storage drawers.

**Comment by Saenaria** [comment]
That would be one way, I can think of a couple other ways so I don't have to pull all the drives out of my system. Thank you for your time and information on this subject.
